[book]
authors = ["Karl David Hedgren", "Love Lyckaro"]
language = "en"
multilingual = false
src = "src"
title = "Data101"

[preprocessor.data101]
command = "./preprocessor/target/release/preprocessor-data101"
